module.exports = [
  'amazon',
  'amazon store',
  'amazon store card',
  'american',
  'american eagle',
  'american education',
  'american education services',
  'aes',
  'amex',
  'american express',
  'bmo harris',
  'banana republic',
  'boa',
  'bank of america',
  'bank of hawaii',
  'bank of the west',
  'barclay',
  'barclays',
  'belk',
  'bestbuy',
  'best buy',
  'boscov\'s',
  'boscov',
  'brooks',
  'brooks brothers',
  'buckle',
  'capital one',
  'capitalone',
  'catherines',
  'cenlar',
  'cenlar fsb',
  'chase',
  'chase connect',
  'chevron',
  'chevron advantage',
  'citi',
  'citibank',
  'commonbond',
  'commonbond firstmark',
  'firstmark',
  'firstmark services',
  'cornerstone',
  'crate and barrel',
  'crate & barrel',
  'crate&barrel',
  'credit one',
  'credit one bank',
  'dell',
  'dell financial',
  'dell financial services',
  'dicks sporting goods',
  'dick\'s sporting goods',
  'discover',
  'etrade',
  'etrade financial',
  'e*trade',
  'e*trade financial',
  'edfinancial',
  'edfinancial services',
  'eddie Bauer',
  'evine',
  'fed',
  'fedloan',
  'fedloan servicing',
  'pheaa',
  'fifth third',
  'fifth third bank',
  'first premier',
  'first premier bank',
  'flagstar',
  'flagstar bank',
  'gm',
  'general motors',
  'gap',
  'golden 1',
  'golden one',
  'golden one credit',
  'golden one credit union',
  'google',
  'google store',
  'google store financing',
  'google store financial',
  'gsmr',
  'granite state',
  'granite state management',
  'granite state management & resources',
  'great lakes',
  'hsn',
  'home shopping',
  'home shopping network',
  'home depot',
  'jcrew',
  'j. crew',
  'j crew',
  'jjill',
  'j. jill',
  'j jill',
  'jcpenny',
  'jcpenny',
  'keybank',
  'kubota',
  'lowes',
  'lowe\'s',
  'mohela',
  'mohela education',
  'mohela education loan',
  'mohela education loan finance',
  'mohela sofi',
  'sofi',
  'mohela laurel',
  'mohela laurel road',
  'mohela laurelroad',
  'laurelroad',
  'laurel road',
  'marvel',
  'mens wearhouse',
  'men\'s wearhouse',
  'navient',
  'nelnet',
  'ny & co',
  'newyork & co',
  'new york & co',
  'osla',
  'oklahoma',
  'oklahoma student',
  'oklahoma student loan',
  'oklahoma student loan authority',
  'office depot',
  'old navy',
  'pnc',
  'pnc bank',
  'paypal',
  'pay pal',
  'peebles',
  'pentagon',
  'pentagon fcu',
  'pentagon federal',
  'pentagon federal credit union',
  'pottery barn',
  'qvc',
  'quicken',
  'quicken loans',
  'rocket',
  'rocket mortgage',
  'regions',
  'regions bank',
  'sallie',
  'sallie mae',
  'sams club',
  'sam\'s club',
  'sears',
  'shell',
  'simmons',
  'simmons first',
  'simmons first bank',
  'simmons first national bank',
  'suntrust',
  'sunoco',
  'toys r us',
  'tractor supply',
  'tractor supply company',
  'us bank',
  'u.s. bank',
  'u.s. bank',
  'umb',
  'umbbank',
  'umb bank',
  'umb financial',
  'usaa',
  'verizon',
  'vsac',
  'vermont student',
  'vermont student assistance',
  'vermont student assistance corporation',
  'victorias secret',
  'victoria\'s secret',
  'wells',
  'wells fargo',
  'fargo',
];
